# This is a basic workflow to help you get started with Actions

name: CI_ubuntu

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
                
      - name: download dependency
        run: |
          git branch -a
          git submodule update --init --recursive            

      - name: build python module
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libglfw3-dev
          python3 --version

          cd src_pybind/core
          mkdir buildMake
          cd buildMake
          cmake ..
          make
          cd ../../../

          cd src_pybind/gl
          mkdir buildMake
          cd buildMake
          cmake ..
          make
          cd ../../../

          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install -e .
          
      - name: test python module
        run: |
          sudo apt-get install python3-opengl
          python3 -m pip install pytest
          python3 -m pip install PyOpenGL
          python3 -m pip install glfw
          python3 -m pip install PySide2
          python3 -m pytest -v -s --is_gl=false --ignore=test_py/test_pyqt.py
          
      - name: torch extension
        run: |
          python3 -m pip uninstall torch_delfem2 -y
          python3 -m pip install torch
          python3 -m pip install -e src_pybind/torch
